name: Player-Home-Teleport
version: ${project.version}
main: tv.ph16.playerhometeleport.Plugin
api-version: 1.15
load: STARTUP
authors: [ shmuelie ]
description: Teleport to players homes
commands:
  home:
    description: "Interact with player homes"
    usage: "/home [set|remove|list|PlayerName]"
libraries:
  - org.jetbrains:annotations:20.1.0